"""LinJ 类型定义模块

提供跨多个后端实现的通用类型定义
"""

from .common import *

__all__ = [
    "NodeID",
    "PathString",
    "StateValue",
    "MappingValue",
    "ToolName",
    "ToolArgs",
    "ToolResult",
    "NodeList",
    "EdgeList",
    "StateDict",
    "StateSnapshot",
    "ConditionExpression",
    "ConditionResult",
    "ContractType",
    "RequiredFields",
    "ContractProperties",
    "ExecutionID",
    "StepID",
    "Revision",
    "ErrorMessage",
    "ErrorDetails",
    "SourcePath",
    "TargetPath",
    "DefaultValue",
    "PathKey",
    "PathSegmentList",
    "DependencySet",
    "Weight",
    "WriteOperations",
    "DeleteOperations",
    "LoopMode",
    "StopCondition",
    "MaxRounds",
    "MaxSteps",
    "MaxRoundsPolicy",
    "TimeoutMs",
    "RetryPolicy",
    "MaxArrayLength",
    "MaxLocalStateBytes",
    "DomainLabel",
    "PlacementTarget",
    "ValidationErrors",
    "ValidationWarnings",
    "TraceEvent",
    "TraceData",
    "TraceLevel",
]
