"""LinJ 共享组件库

提供跨多个后端实现的核心组件、类型定义和异常处理。
"""

from .core import *
from .types import *
from .exceptions import *

__version__ = "0.1.0"
__all__ = [
    # Core components
    "PathResolver",
    "PathSegment",
    "ChangeSet",
    "ChangeSetBuilder",
    "WriteOp",
    "DeleteOp",
    "StateManager",
    "StateView",
    "Node",
    "HintNode",
    "ToolNode",
    "JoinNode",
    "GateNode",
    "NodeType",
    "ValueRef",
    "Contract",
    "NodePolicy",
    "ToolCall",
    "Effect",
    "GlossaryItem",
    "parse_node",
    "Edge",
    "EdgeKind",
    "MapRule",
    "DependencyGraph",
    "LinJDocument",
    "Policies",
    "Loop",
    "Placement",
    "Requirements",
    "ContractValidator",
    "ValidationResult",
    "ContractValidationError",
    "DiagnosticTracer",
    "TraceEntry",
    "PerformanceMetrics",
    "ConflictRecord",
    "TracingMixin",
    "LogLevel",
    # Types
    "NodeID",
    "PathString",
    "StateValue",
    "MappingValue",
    "ToolName",
    "ToolArgs",
    "ToolResult",
    "NodeList",
    "EdgeList",
    "StateDict",
    "StateSnapshot",
    "ConditionExpression",
    "ConditionResult",
    "ContractType",
    "RequiredFields",
    "ContractProperties",
    "ExecutionID",
    "StepID",
    "Revision",
    "ErrorMessage",
    "ErrorDetails",
    "SourcePath",
    "TargetPath",
    "DefaultValue",
    "PathKey",
    "PathSegmentList",
    "DependencySet",
    "Weight",
    "WriteOperations",
    "DeleteOperations",
    "LoopMode",
    "StopCondition",
    "MaxRounds",
    "MaxSteps",
    "MaxRoundsPolicy",
    "TimeoutMs",
    "RetryPolicy",
    "MaxArrayLength",
    "MaxLocalStateBytes",
    "DomainLabel",
    "PlacementTarget",
    "ValidationErrors",
    "ValidationWarnings",
    "TraceEvent",
    "TraceData",
    "TraceLevel",
    # Exceptions
    "LinJError",
    "ValidationError",
    "ExecutionError",
    "MappingError",
    "ConditionError",
    "ConflictError",
    "HandleExpired",
    "ResourceConstraintUnsatisfied",
    "InvalidRequirements",
    "InvalidPlacement",
    "ContractViolation",
]
